import{a as p,i as c,S as b}from"./assets/vendor-BH9GyP-n.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&a(n)}).observe(document,{childList:!0,subtree:!0});function o(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(t){if(t.ep)return;t.ep=!0;const r=o(t);fetch(t.href,r)}})();function f(e){return e.map(({webformatURL:s,largeImageURL:o,tags:a,likes:t,views:r,comments:n,downloads:y})=>`
        <li class="gallery-item">
            <a href="${o}" class="gallery-link">
                <img src="${s}" alt="${a}" loading="lazy" />
            </a>
            <div class="info">
                <p class="info-item"><b>Likes</b> ${t}</p>
                <p class="info-item"><b>Views</b> ${r}</p>
                <p class="info-item"><b>Comments</b> ${n}</p>
                <p class="info-item"><b>Downloads</b> ${y}</p>
            </div>
        </li>
    `).join("")}function L(){const e=document.querySelector(".gallery");e&&(e.innerHTML="")}function v(){const e=document.querySelector(".loader");e&&(console.log("loader on"),e.classList.add("visible"))}function u(){const e=document.querySelector(".loader");e&&(console.log("loader off"),e.classList.remove("visible"))}const S="49643182-9754596b7a63617f9fa0f6656";async function m(e,s){return await p.get("https://pixabay.com/api/",{params:{key:S,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:s,per_page:15}})}const q=document.querySelector(".form"),h=document.querySelector("input[name='search-text']"),g=document.querySelector(".gallery");document.querySelector(".loader").style.display="none";const i=document.querySelector(".load-more");q.addEventListener("submit",w);i.addEventListener("click",E);let l=1,d=null;function w(e){e.preventDefault();const s=h.value.trim();s&&(l=1,L(),v(),m(s,l).then(o=>{if(u(),!o.data.hits||o.data.hits.length===0){c.warning({title:"No Results",message:"No images found for your query. Try something else!",position:"topRight"});return}g.innerHTML=f(o.data.hits),i.style.display="block";const a=Math.ceil(o.data.totalHits/15);l<a?(i.classList.remove("load-more-hidden"),i.classList.add("load-more")):(i.classList.remove("load-more"),i.classList.add("load-more-hidden"),c.info({title:"End of Results",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})),d?d.refresh():d=new b(".gallery a",{captions:!0,captionDelay:250,close:!0})}).catch(o=>{u(),console.error(o),c.error({title:"Error",message:"Sorry, something went wrong. Please try again!",position:"topRight"})}))}function E(){l++,i.disabled=!0,m(h.value.trim(),l).then(e=>{g.insertAdjacentHTML("beforeend",f(e.data.hits)),i.disabled=!1;const s=Math.ceil(e.data.totalHits/15);(!e.data.hits||e.data.hits.length===0||l>=s)&&(i.classList.remove("load-more"),i.classList.add("load-more-hidden"),c.info({title:"End of Results",message:"You've reached the end of search results.",position:"topRight"}));const o=document.querySelectorAll(".gallery-item");if(o.length===0)return;const a=o[o.length-1].getBoundingClientRect().height;window.scrollBy({left:0,top:a*2,behavior:"smooth"}),d&&d.refresh()}).catch(e=>{i.classList.remove("load-more"),i.classList.add("load-more-hidden"),c.error({title:"Error",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})})}
//# sourceMappingURL=index.js.map
