import{a as w,i as a,S}from"./assets/vendor-BH9GyP-n.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))d(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&d(n)}).observe(document,{childList:!0,subtree:!0});function i(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function d(t){if(t.ep)return;t.ep=!0;const r=i(t);fetch(t.href,r)}})();function p(e){return e.map(({webformatURL:o,largeImageURL:i,tags:d,likes:t,views:r,comments:n,downloads:L})=>`
        <li class="gallery-item">
            <a href="${i}" class="gallery-link">
                <img src="${o}" alt="${d}" loading="lazy" />
            </a>
            <div class="info">
                <p class="info-item"><b>Likes</b> ${t}</p>
                <p class="info-item"><b>Views</b> ${r}</p>
                <p class="info-item"><b>Comments</b> ${n}</p>
                <p class="info-item"><b>Downloads</b> ${L}</p>
            </div>
        </li>
    `).join("")}function v(){const e=document.querySelector(".gallery");e&&(e.innerHTML="")}function y(){const e=document.querySelector(".loader");e&&(console.log("loader on"),e.classList.add("visible"))}function u(){const e=document.querySelector(".loader");e&&(console.log("loader off"),e.classList.remove("visible"))}const q="49643182-9754596b7a63617f9fa0f6656";async function m(e,o){return await w.get("https://pixabay.com/api/",{params:{key:q,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:15}})}const E=document.querySelector(".form"),g=document.querySelector("input[name='search-text']"),h=document.querySelector(".gallery");document.querySelector(".loader").style.display="none";const s=document.querySelector(".load-more");E.addEventListener("submit",M);s.addEventListener("click",R);let c=1,l=null;const P=15;let b=0;loader.style.display="none";function f(){const e=Math.ceil(b/P);c>=e?(s.style.display="none",a.info({title:"End of Results",message:"You've reached the end of search results.",position:"topRight"})):s.style.display="block"}async function M(e){e.preventDefault();const o=g.value.trim();if(!o){a.warning({title:"Empty Query",message:"Please enter a search term!",position:"topRight"});return}c=1,v(),y();try{const i=await m(o,c);if(u(),!i.data.hits||i.data.hits.length===0){a.warning({title:"No Results",message:"No images found for your query. Try something else!",position:"topRight"}),s.style.display="none";return}b=i.data.totalHits,h.innerHTML=p(i.data.hits),f(),l?l.refresh():l=new S(".gallery a",{captions:!0,captionDelay:250,close:!0})}catch(i){u(),s.style.display="none",a.error({title:"Error",message:"Something went wrong. Please try again!",position:"topRight"}),console.error(i)}}async function R(){c++,s.disabled=!0,y();try{const e=await m(g.value.trim(),c);if(u(),s.disabled=!1,!e.data.hits||e.data.hits.length===0){f();return}h.insertAdjacentHTML("beforeend",p(e.data.hits)),f();const o=document.querySelectorAll(".gallery-item");if(o.length>0){const i=o[o.length-1].getBoundingClientRect().height;window.scrollBy({left:0,top:i*2,behavior:"smooth"})}l&&l.refresh()}catch(e){u(),s.style.display="none",a.error({title:"Error",message:"Something went wrong during loading.",position:"topRight"}),console.error(e)}}
//# sourceMappingURL=index.js.map
