import{a as S,i as a,S as v}from"./assets/vendor-BH9GyP-n.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))d(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&d(n)}).observe(document,{childList:!0,subtree:!0});function i(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function d(t){if(t.ep)return;t.ep=!0;const r=i(t);fetch(t.href,r)}})();function y(e){return e.map(({webformatURL:o,largeImageURL:i,tags:d,likes:t,views:r,comments:n,downloads:w})=>`
        <li class="gallery-item">
            <a href="${i}" class="gallery-link">
                <img src="${o}" alt="${d}" loading="lazy" />
            </a>
            <div class="info">
                <p class="info-item"><b>Likes</b> ${t}</p>
                <p class="info-item"><b>Views</b> ${r}</p>
                <p class="info-item"><b>Comments</b> ${n}</p>
                <p class="info-item"><b>Downloads</b> ${w}</p>
            </div>
        </li>
    `).join("")}function q(){const e=document.querySelector(".gallery");e&&(e.innerHTML="")}function m(){const e=document.querySelector(".loader");e&&(console.log("loader on"),e.classList.add("visible"))}function u(){const e=document.querySelector(".loader");e&&(console.log("loader off"),e.classList.remove("visible"))}const E="49643182-9754596b7a63617f9fa0f6656";async function g(e,o){return await S.get("https://pixabay.com/api/",{params:{key:E,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:15}})}const P=document.querySelector(".form"),h=document.querySelector("input[name='search-text']"),b=document.querySelector(".gallery"),f=document.querySelector(".loader"),s=document.querySelector(".load-more");f&&(f.style.display="none");P.addEventListener("submit",R);s.addEventListener("click",$);let c=1,l=null;const M=15;let L=0;f.style.display="none";function p(){const e=Math.ceil(L/M);c>=e?(s.style.display="none",a.info({title:"End of Results",message:"You've reached the end of search results.",position:"topRight"})):s.style.display="block"}async function R(e){e.preventDefault();const o=h.value.trim();if(!o){a.warning({title:"Empty Query",message:"Please enter a search term!",position:"topRight"});return}c=1,q(),m();try{const i=await g(o,c);if(u(),!i.data.hits||i.data.hits.length===0){a.warning({title:"No Results",message:"No images found for your query. Try something else!",position:"topRight"}),s.style.display="none";return}L=i.data.totalHits,b.innerHTML=y(i.data.hits),p(),l?l.refresh():l=new v(".gallery a",{captions:!0,captionDelay:250,close:!0})}catch(i){u(),s.style.display="none",a.error({title:"Error",message:"Something went wrong. Please try again!",position:"topRight"}),console.error(i)}}async function $(){c++,s.disabled=!0,m();try{const e=await g(h.value.trim(),c);if(u(),s.disabled=!1,!e.data.hits||e.data.hits.length===0){p();return}b.insertAdjacentHTML("beforeend",y(e.data.hits)),p();const o=document.querySelectorAll(".gallery-item");if(o.length>0){const i=o[o.length-1].getBoundingClientRect().height;window.scrollBy({left:0,top:i*2,behavior:"smooth"})}l&&l.refresh()}catch(e){u(),s.style.display="none",a.error({title:"Error",message:"Something went wrong during loading.",position:"topRight"}),console.error(e)}}
//# sourceMappingURL=index.js.map
